### ISSUE TITLE
Caused by: java.sql.SQLSyntaxErrorException: Table 'flowable-spring-boot.act_id_user' doesn't exist

### ISSUE THREAD

**Issue by tomcatGu** [flowable/flowable-examples#6]
I am following the spring-boot-example with MySQL 5.0. When the app run there output some errors.
The part output:
Caused by: org.flowable.engine.common.api.FlowableException: couldn't upgrade db schema: alter table ACT_ID_USER add TENANT_ID_ varchar(255) default ''
	at org.flowable.engine.common.impl.db.AbstractSqlScriptBasedDbSchemaManager.executeSchemaResource(AbstractSqlScriptBasedDbSchemaManager.java:338) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.db.AbstractSqlScriptBasedDbSchemaManager.executeSchemaResource(AbstractSqlScriptBasedDbSchemaManager.java:230) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.db.AbstractSqlScriptBasedDbSchemaManager.dbSchemaUpgrade(AbstractSqlScriptBasedDbSchemaManager.java:94) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.db.ServiceSqlScriptBasedDbSchemaManager.dbSchemaUpdate(ServiceSqlScriptBasedDbSchemaManager.java:78) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.idm.engine.impl.db.IdmDbSchemaManager.performSchemaOperationsIdmEngineBuild(IdmDbSchemaManager.java:154) ~[flowable-idm-engine-6.3.0.jar:6.3.0]
	at org.flowable.idm.engine.impl.SchemaOperationsIdmEngineBuild.execute(SchemaOperationsIdmEngineBuild.java:29) ~[flowable-idm-engine-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.interceptor.DefaultCommandInvoker.execute(DefaultCommandInvoker.java:10) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.idm.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:49) ~[flowable-idm-spring-6.3.0.jar:6.3.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.flowable.idm.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:46) ~[flowable-idm-spring-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.idm.engine.impl.IdmEngineImpl.<init>(IdmEngineImpl.java:45) ~[flowable-idm-engine-6.3.0.jar:6.3.0]
	at org.flowable.idm.engine.IdmEngineConfiguration.buildIdmEngine(IdmEngineConfiguration.java:173) ~[flowable-idm-engine-6.3.0.jar:6.3.0]
	at org.flowable.idm.spring.SpringIdmEngineConfiguration.buildIdmEngine(SpringIdmEngineConfiguration.java:48) ~[flowable-idm-spring-6.3.0.jar:6.3.0]
	at org.flowable.spring.configurator.SpringIdmEngineConfigurator.configure(SpringIdmEngineConfigurator.java:37) ~[flowable-spring-6.3.0.jar:6.3.0]
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.configuratorsAfterInit(ProcessEngineConfigurationImpl.java:1417) ~[flowable-engine-6.3.0.jar:6.3.0]
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.init(ProcessEngineConfigurationImpl.java:886) ~[flowable-engine-6.3.0.jar:6.3.0]
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:798) ~[flowable-engine-6.3.0.jar:6.3.0]
	at org.flowable.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:74) ~[flowable-spring-6.3.0.jar:6.3.0]
	at org.flowable.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:60) ~[flowable-spring-6.3.0.jar:6.3.0]
	at org.flowable.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32) ~[flowable-spring-6.3.0.jar:6.3.0]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 59 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'flowable-spring-boot.act_id_user' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:891) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:795) ~[mysql-connector-java-6.0.6.jar:6.0.6]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-2.7.9.jar:na]
	at org.flowable.engine.common.impl.db.AbstractSqlScriptBasedDbSchemaManager.executeSchemaResource(AbstractSqlScriptBasedDbSchemaManager.java:309) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	... 83 common frames omitted

How can I resolve this problem?

**Comment by saikatsain** [comment]
Try using mysql-connector version 5.1.44
